# Generated by Django 4.2.4 on 2023-08-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='favicon',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
