# Generated by Django 4.2.4 on 2023-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_categories',
            field=models.ManyToManyField(to='backend.subcategory'),
        ),
    ]
