# Generated by Django 4.2.4 on 2023-10-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_pages_sections_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmenu',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagesections',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primarymenu',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
    ]
