# Generated by Django 4.2.4 on 2023-10-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_category_site_id_childmenu_site_id_files_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sections',
            name='orders',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='page_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sections',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.site'),
            preserve_default=False,
        ),
    ]
